"""
Synthetic dataset generation (P7).

ALL DATA PRODUCED HERE IS SYNTHETIC. No public credit dataset was available under
data/raw/, so customer financial profiles are generated, not sourced. Every file
carries a header comment saying so and a SYNTHETIC column on every row, so the fact
survives being opened in a spreadsheet, re-saved, or partially copied
(CONTEXT.md section 11).

These people do not exist. This is not banking history and must never be presented
as any.

OFFLINE ONLY. Lives in training/, never imported by app/. Run:

    python -m training.generate_data
"""

import csv
import random
from pathlib import Path

from app.schemas.enums import (
    AssetType,
    EmploymentType,
    FeedbackEventType,
    FinancingStrategy,
    LoanPurpose,
    RiskAppetite,
)

DATA_DIR = Path("data")
SEED = 20260902
# 1200, not 400. The risk classifier learns a ~11% default rate, so 400 customers left
# roughly 46 positives and only ~10 in the held-out split — a test ROC-AUC computed on
# ten positives is dominated by draw noise, not by model quality. Tripling the
# population costs a minute of offline runtime and is the only honest way to shrink
# that variance in a synthetic dataset.
N_CUSTOMERS = 1200

# Share of customers deliberately generated with NO portfolio. The zero-portfolio
# path is first-class (CONTEXT.md non-negotiable 16), so it must be well represented
# in training, not a rare edge case the model never learns.
NO_PORTFOLIO_SHARE = 0.30

# Share of customers given seed interaction history. The rest are cold-start, which
# is likewise a first-class path.
WITH_HISTORY_SHARE = 0.40

SYNTHETIC_HEADER = (
    "# SYNTHETIC DATA — generated by training/generate_data.py. These customers, "
    "portfolios and interactions are fabricated. Not real banking data. Loan product "
    "lender names are real Indian lenders; their rates and limits are APPROXIMATE "
    "figures near published rate cards, not quotes, and imply no offer or approval."
)


# ---------------------------------------------------------------- catalogue

# 16 products spanning six purposes and eight real Indian lenders. Lender names and
# product names are real; rates, limits and eligibility floors are APPROXIMATE figures
# in the neighbourhood of published Sept-2026 rate cards, not quotes. No approval is
# implied by presence here.
#
# The rate spread is deliberately wide (8.15% education to 18.00% NBFC business),
# because it is real: Indian secured lending is cheap and NBFC unsecured lending is
# not. A catalogue compressed into a narrow cheap band makes borrowing dominate every
# financing decision and collapses strategy diversity in the labels.
PRODUCTS = [
    # product_id, lender, name, purposes, rate, min_amt, max_amt, min_ten, max_ten, min_cs, min_inc, fee
    ("HL-101", "SBI", "SBI Home Loan (Regular)", [LoanPurpose.HOME], 8.50, 300_000, 75_000_000, 60, 360, 650, 25_000, 0.35),
    ("HL-102", "HDFC Bank", "HDFC Bank Home Loan", [LoanPurpose.HOME], 8.75, 500_000, 100_000_000, 60, 360, 700, 30_000, 0.50),
    ("HL-103", "ICICI Bank", "ICICI Bank Home Loan", [LoanPurpose.HOME], 8.75, 300_000, 100_000_000, 60, 360, 700, 25_000, 0.50),
    ("HL-104", "LIC Housing Finance", "LIC HFL Griha Suvidha", [LoanPurpose.HOME], 8.60, 200_000, 150_000_000, 60, 360, 640, 22_000, 0.25),
    ("VL-201", "SBI", "SBI New Car Loan", [LoanPurpose.VEHICLE], 9.20, 100_000, 5_000_000, 12, 84, 700, 25_000, 0.50),
    ("VL-202", "HDFC Bank", "HDFC Bank Car Loan", [LoanPurpose.VEHICLE], 9.40, 100_000, 10_000_000, 12, 84, 700, 25_000, 0.50),
    ("VL-203", "Bajaj Finserv", "Bajaj Used Car & Two-Wheeler Loan", [LoanPurpose.VEHICLE], 13.50, 50_000, 1_500_000, 12, 60, 640, 18_000, 2.00),
    ("EL-301", "SBI", "SBI Scholar Loan", [LoanPurpose.EDUCATION], 8.15, 400_000, 7_500_000, 12, 180, 600, 0, 0.00),
    ("EL-302", "Bank of Baroda", "Baroda Scholar", [LoanPurpose.EDUCATION], 8.40, 400_000, 12_500_000, 12, 180, 600, 0, 0.00),
    ("EL-303", "Axis Bank", "Axis Bank Education Loan (Unsecured)", [LoanPurpose.EDUCATION], 13.70, 50_000, 7_500_000, 12, 180, 640, 15_000, 1.00),
    ("PL-401", "HDFC Bank", "HDFC Bank Personal Loan", [LoanPurpose.PERSONAL, LoanPurpose.MEDICAL], 10.90, 50_000, 4_000_000, 12, 60, 720, 25_000, 1.50),
    ("PL-402", "ICICI Bank", "ICICI Bank Personal Loan", [LoanPurpose.PERSONAL], 11.25, 50_000, 5_000_000, 12, 60, 720, 25_000, 1.50),
    ("PL-403", "Bajaj Finserv", "Bajaj Flexi Personal Loan", [LoanPurpose.PERSONAL, LoanPurpose.MEDICAL], 16.00, 30_000, 4_000_000, 12, 60, 685, 20_000, 2.50),
    ("ML-501", "SBI", "SBI Aarogya Plus Medical Loan", [LoanPurpose.MEDICAL], 10.50, 50_000, 1_500_000, 12, 60, 650, 20_000, 0.50),
    ("BL-601", "SBI", "SBI SME Business Loan", [LoanPurpose.BUSINESS], 9.75, 500_000, 25_000_000, 12, 120, 700, 50_000, 1.00),
    ("BL-602", "IIFL Finance", "IIFL Business Loan", [LoanPurpose.BUSINESS], 18.00, 100_000, 3_000_000, 12, 60, 650, 30_000, 2.75),
]

# Per-purpose requirement shape: (min multiple of annual income, max multiple,
# plausible tenures). Tenures are chosen to overlap the catalogue's own limits for
# that purpose, so eligibility failures reflect the customer, not the draw.
REQUIREMENT_SHAPE = {
    LoanPurpose.HOME: (1.0, 4.5, [60, 84, 120, 180, 240]),
    LoanPurpose.VEHICLE: (0.25, 1.4, [12, 24, 36, 48, 60, 84]),
    LoanPurpose.EDUCATION: (0.4, 2.2, [24, 36, 48, 60, 84, 120]),
    LoanPurpose.PERSONAL: (0.15, 0.9, [12, 24, 36, 48]),
    LoanPurpose.MEDICAL: (0.10, 0.7, [12, 24, 36, 48, 60]),
    LoanPurpose.BUSINESS: (0.4, 2.5, [24, 36, 48, 60, 84, 120]),
}

# Employment mix of the Indian retail-borrowing population. Uniform draws over the
# four enum values overstate CONTRACT and RETIRED borrowers badly; formal-sector
# salaried applicants dominate a lender's actual funnel, with self-employed second.
EMPLOYMENT_MIX_TYPES = [
    EmploymentType.SALARIED,
    EmploymentType.SELF_EMPLOYED,
    EmploymentType.CONTRACT,
    EmploymentType.RETIRED,
]
EMPLOYMENT_MIX_WEIGHTS = [0.55, 0.28, 0.12, 0.05]

# Portfolio archetypes: (weights per asset type, relative size in months of income).
# Deliberately varied so the population is not dominated by one shape — including a
# volatile-heavy archetype, without which the volatile-liquidation guardrail is
# unreachable in practice (P6 finding).
PORTFOLIO_ARCHETYPES = {
    "cash_heavy": {AssetType.CASH: 0.55, AssetType.FIXED_DEPOSIT: 0.35, AssetType.MUTUAL_FUNDS: 0.10},
    "balanced": {AssetType.CASH: 0.15, AssetType.FIXED_DEPOSIT: 0.25, AssetType.MUTUAL_FUNDS: 0.30, AssetType.STOCKS: 0.20, AssetType.BONDS: 0.10},
    "equity_tilted": {AssetType.CASH: 0.08, AssetType.MUTUAL_FUNDS: 0.32, AssetType.STOCKS: 0.50, AssetType.BONDS: 0.10},
    "volatile_heavy": {AssetType.CASH: 0.05, AssetType.STOCKS: 0.55, AssetType.CRYPTO: 0.40},
    "conservative_income": {AssetType.FIXED_DEPOSIT: 0.45, AssetType.BONDS: 0.40, AssetType.CASH: 0.15},
}


def _write(path: Path, header: list[str], rows: list[list]) -> None:
    """
    Write a CSV with a leading comment line, then the header, then rows.

    READERS MUST SKIP LINES BEGINNING WITH '#'. The comment is deliberate: a file
    that loses its provenance when someone opens it is a file that will eventually be
    mistaken for real data.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        handle.write(SYNTHETIC_HEADER + "\n")
        writer = csv.writer(handle)
        writer.writerow(header)
        writer.writerows(rows)


def generate_products() -> list[list]:
    return [
        [
            product_id,
            lender,
            name,
            "|".join(p.value for p in purposes),
            rate,
            min_amount,
            max_amount,
            min_tenure,
            max_tenure,
            min_credit_score,
            min_income,
            fee,
            "TRUE",
        ]
        for (
            product_id,
            lender,
            name,
            purposes,
            rate,
            min_amount,
            max_amount,
            min_tenure,
            max_tenure,
            min_credit_score,
            min_income,
            fee,
        ) in PRODUCTS
    ]


def generate_customers(rng: random.Random) -> list[list]:
    """
    Customers spread across income bands, credit tiers and appetites.

    The spread is deliberately wide, including customers who will turn out to have no
    good option. A population where everyone has a suitable loan cannot teach the
    model that some profiles do not (CONTEXT.md section 7).
    """
    rows = []
    for index in range(N_CUSTOMERS):
        user_id = f"syn-{index:04d}"

        # Log-uniform income, so the population is not concentrated in one band and
        # scale-dependent bugs in the policy have room to show. The band is set to the
        # Indian salaried/self-employed borrowing population a retail lender actually
        # sees: roughly Rs 25,000 to Rs 5,00,000 per month.
        income = round(10 ** rng.uniform(4.4, 5.7), -2)  # ~25,000 to ~500,000
        # Outgoings leave a real but variable margin. The upper end still produces
        # customers with almost no headroom — those are the ones who legitimately have
        # no good option, and the dataset needs them.
        expenses = round(income * rng.uniform(0.25, 0.72), -2)
        existing_emi = round(income * rng.uniform(0.0, 0.18), -2)

        credit_score = int(min(900, max(300, rng.gauss(710, 85))))
        employment = rng.choices(EMPLOYMENT_MIX_TYPES, weights=EMPLOYMENT_MIX_WEIGHTS)[0]
        employment_years = round(abs(rng.gauss(6.0, 4.5)), 1)
        age = rng.randint(23, 62)
        dependents = rng.choice([0, 0, 1, 2, 2, 3])

        # Requirement and tenure are drawn PER PURPOSE. A uniform draw across all
        # purposes generated people asking for a 12-month home loan or eight times
        # their annual income for a medical bill, which no product serves — the
        # resulting attrition was an artifact of the generator, not a real signal
        # about the catalogue.
        purpose = rng.choice(list(LoanPurpose))
        low, high, tenures = REQUIREMENT_SHAPE[purpose]
        annual_income = income * 12
        required_amount = round(annual_income * rng.uniform(low, high), -3)
        preferred_tenure = rng.choice(tenures)
        appetite = rng.choice(list(RiskAppetite))

        rows.append(
            [
                user_id,
                income,
                expenses,
                existing_emi,
                credit_score,
                employment.value,
                employment_years,
                age,
                dependents,
                purpose.value,
                required_amount,
                preferred_tenure,
                appetite.value,
                "TRUE",
            ]
        )
    return rows


def generate_portfolios(rng: random.Random, incomes: dict[str, float]) -> list[list]:
    """
    One row per holding. Customers with no portfolio simply have no rows — the
    zero-portfolio path is an absence, not a row of zeros.

    Portfolio size is drawn as a MULTIPLE OF THE OWNER'S MONTHLY INCOME, not as a
    free-standing absolute. Drawing it independently produced a population where a
    Rs 25,000/month earner could hold Rs 1.5 crore while a Rs 5,00,000/month earner
    held Rs 50,000 — the two quantities are strongly correlated in reality, and
    breaking that correlation also broke the financing decision: liquidation was
    viable for the wrong people and unavailable to the right ones, so BORROW_100 won
    a degenerate share of groups.
    """
    rows = []
    for user_id, income in incomes.items():
        if rng.random() < NO_PORTFOLIO_SHARE:
            continue
        archetype_name = rng.choice(list(PORTFOLIO_ARCHETYPES))
        weights = PORTFOLIO_ARCHETYPES[archetype_name]
        # ~2x to ~250x monthly income, i.e. two months' to roughly twenty years' of
        # accumulated savings. Wide on purpose: the thin-savings and the
        # substantial-corpus borrower must both be well represented.
        total_value = round(income * 10 ** rng.uniform(0.3, 2.4), -2)
        for asset_type, weight in weights.items():
            current = round(total_value * weight, 2)
            if current <= 0:
                continue
            # Gains and losses both occur, so unrealized_gain_loss is not one-signed.
            invested = round(current / rng.uniform(0.65, 1.45), 2)
            rows.append(
                [user_id, archetype_name, asset_type.value, current, invested, "TRUE"]
            )
    return rows


def generate_history(rng: random.Random, customer_ids: list[str]) -> list[list]:
    """
    Seed interaction history for a subset. The rest are cold-start, which the
    personalization layer treats as a first-class path.
    """
    rows = []
    product_ids = [p[0] for p in PRODUCTS]
    for user_id in customer_ids:
        if rng.random() >= WITH_HISTORY_SHARE:
            continue
        sessions = rng.randint(1, 5)
        for _ in range(sessions):
            product_id = rng.choice(product_ids)
            purpose = rng.choice(list(LoanPurpose))
            days_ago = round(rng.uniform(1, 540), 1)
            tenure = rng.choice([12, 24, 36, 48, 60, 84, 120])
            strategy = rng.choice(list(FinancingStrategy))
            rows.append(
                [
                    user_id,
                    "RECOMMENDATION",
                    days_ago,
                    product_id,
                    purpose.value,
                    round(10 ** rng.uniform(5.0, 6.8), -2),
                    tenure,
                    strategy.value,
                    round(rng.uniform(0.3, 0.95), 3),
                    "RECOMMENDED",
                    "",
                    "TRUE",
                ]
            )
            event = rng.choices(
                list(FeedbackEventType), weights=[0.5, 0.25, 0.25], k=1
            )[0]
            rows.append(
                [
                    user_id,
                    "EVENT",
                    max(0.1, days_ago - rng.uniform(0.0, 1.0)),
                    product_id,
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    event.value,
                    "TRUE",
                ]
            )
    return rows


def main() -> None:
    rng = random.Random(SEED)

    _write(
        DATA_DIR / "loan_products.csv",
        [
            "product_id",
            "lender",
            "product_name",
            "purposes",
            "annual_rate",
            "min_amount",
            "max_amount",
            "min_tenure_months",
            "max_tenure_months",
            "min_credit_score",
            "min_monthly_income",
            "processing_fee_pct",
            "SYNTHETIC",
        ],
        generate_products(),
    )

    customers = generate_customers(rng)
    _write(
        DATA_DIR / "customers.csv",
        [
            "user_id",
            "monthly_income",
            "monthly_expenses",
            "existing_emi",
            "credit_score",
            "employment_type",
            "employment_years",
            "age",
            "dependents",
            "purpose",
            "required_amount",
            "preferred_tenure_months",
            "risk_appetite",
            "SYNTHETIC",
        ],
        customers,
    )

    customer_ids = [row[0] for row in customers]
    # Column 1 of a customer row is monthly_income (see the customers.csv header).
    incomes = {row[0]: row[1] for row in customers}
    _write(
        DATA_DIR / "portfolios.csv",
        ["user_id", "archetype", "asset_type", "current_value", "invested_value", "SYNTHETIC"],
        generate_portfolios(rng, incomes),
    )
    _write(
        DATA_DIR / "history.csv",
        [
            "user_id",
            "record_type",
            "days_ago",
            "product_id",
            "purpose",
            "amount",
            "tenure",
            "strategy",
            "suitability",
            "status",
            "event_type",
            "SYNTHETIC",
        ],
        generate_history(rng, customer_ids),
    )

    print(f"seed={SEED}")
    print(f"loan_products.csv  {len(PRODUCTS)} products")
    print(f"customers.csv      {len(customers)} customers (ALL SYNTHETIC)")
    for name in ("portfolios.csv", "history.csv"):
        lines = (DATA_DIR / name).read_text(encoding="utf-8").splitlines()
        print(f"{name:18} {len(lines) - 2} rows")


if __name__ == "__main__":
    main()
